name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - master  # 如果您的主分支名称不同，请修改此处

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-

    - name: Install Dependencies
      run: npm install

    - name: Setup Hexo
      run: npm install hexo-cli -g

    - name: Generate Static Files
      run: hexo generate

    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: hexo deploy
